/* expected_future.hpp
Provides a non-allocating expected<T, E> based future-promise
(C) 2014 Niall Douglas http://www.nedprod.com/
File Created: Oct 2014


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef BOOST_EXPECTED_FUTURE_HPP
#define BOOST_EXPECTED_FUTURE_HPP

#include "spinlock.hpp"
#include "expected/include/boost/expected/expected.hpp"

namespace boost
{
  namespace expected_future
  {
    template<class T, class... Args> class basic_promise;
    template<class T, class E> class basic_shared_future;
    template<class T, class E> class basic_future : expected<T, E>
    {
    public:
      BOOST_CONSTEXPR basic_future() BOOST_NOEXCEPT_IF(std::is_nothrow_default_constructible<expected<T, E>>::value) { }
      BOOST_CONSTEXPR basic_future(basic_future &&o) BOOST_NOEXCEPT_IF(std::is_nothrow_move_constructible<expected<T, E>>::value)
        : expected<T, E>(std::move(o)) { }
      basic_future(const basic_future &o) = delete;
      BOOST_CONSTEXPR ~basic_future() BOOST_NOEXCEPT_IF(std::is_nothrow_destructible<expected<T, E>>::value) { }
      BOOST_CONSTEXPR basic_future &operator=(basic_future &&o) BOOST_NOEXCEPT_IF(std::is_nothrow_move_assignable<expected<T, E>>::value);
      basic_future &operator=(const basic_future &o) = delete;
      BOOST_CONSTEXPR basic_shared_future<T, E> share();
    };
    template<class T, class E> class basic_shared_future
    {
    };
    // non-constexpr promise, must vector through a virtual function to set value
    template<class T, class E> class basic_promise<T, E>
    {
    };
    // constexpr promise
    template<template<class, class> future_type, class T, class E,
      class _=std::enable_if<std::is_trivially_constructible<basic_future<T, E>, future_type>::value>
      class basic_promise<future_type<T, E>>
    {
    };
    template<class T, class E=std::exception_ptr> using promise = basic_promise<T, E>;
    template<class T, class E=std::exception_ptr> using future = basic_future<T, E>;
    template<class T, class E=std::exception_ptr> using shared_future = basic_shared_future<T, E>;

  } // namespace expected_future
} // namespace boost

#endif
