// Deliberately without include guard to attempt to include differing versions
// in same translation unit will produce compiler errors
#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang__)
#define BOOST_OUTCOME_HEADERS_PATH2 BOOST_OUTCOME_VERSION_GLUE(v, BOOST_OUTCOME_HEADERS_VERSION, /monad.hpp)
#elif !__PCPP_ALWAYS_FALSE__
#define BOOST_OUTCOME_HEADERS_PATH2 BOOST_OUTCOME_VERSION_GLUE(v, BOOST_OUTCOME_HEADERS_VERSION,)/monad.hpp
#endif


#define BOOST_OUTCOME_HEADERS_PATH4(a) #a
#define BOOST_OUTCOME_HEADERS_PATH3(a) BOOST_OUTCOME_HEADERS_PATH4(a)
//! \brief The Outcome headers path generated by the preprocessor from the version
#define BOOST_OUTCOME_HEADERS_PATH BOOST_OUTCOME_HEADERS_PATH3(BOOST_OUTCOME_HEADERS_PATH2)
#include BOOST_OUTCOME_HEADERS_PATH
#undef BOOST_OUTCOME_HEADERS_PATH
#undef BOOST_OUTCOME_HEADERS_PATH2
