#include "version.hpp"

#if defined(_MSC_VER) && !defined(__clang)
#define BOOST_OUTCOME_HEADERS_PATH2 BOOST_OUTCOME_VERSION_GLUE(v, BOOST_OUTCOME_HEADERS_VERSION, /monad.hpp)
#else
#define BOOST_OUTCOME_HEADERS_PATH2 BOOST_OUTCOME_VERSION_GLUE(v, BOOST_OUTCOME_HEADERS_VERSION,)/monad.hpp
#endif

#undef BOOST_OUTCOME_MODULE_NAME
#if defined(__cpp_modules)
#if defined(_MSC_VER) && !defined(__clang)
#define BOOST_OUTCOME_MODULE_NAME BOOST_OUTCOME_VERSION_GLUE(afio_v, BOOST_OUTCOME_NAMESPACE_VERSION,)
#else
#define BOOST_OUTCOME_MODULE_NAME BOOST_OUTCOME_VERSION_GLUE(afio_v, BOOST_OUTCOME_NAMESPACE_VERSION,)
#endif
#endif

#define BOOST_OUTCOME_HEADERS_PATH4(a) #a
#define BOOST_OUTCOME_HEADERS_PATH3(a) BOOST_OUTCOME_HEADERS_PATH4(a)
#define BOOST_OUTCOME_HEADERS_PATH BOOST_OUTCOME_HEADERS_PATH3(BOOST_OUTCOME_HEADERS_PATH2)
#include BOOST_OUTCOME_HEADERS_PATH
