name: 'Install dependencies'
description: 'This workflow installs dependencies from multiple package managers'
inputs:
  cmake_exec:
    description: 'The cmake executable'
    required: false
    default: 'cmake'
  cc:
    description: 'Path to C compiler.'
    required: false
    default: ''
  cxx:
    description: 'Path to C++ compiler.'
    required: false
    default: ''
  cxxstd:
    description: 'List of standards with which cmake will build and test the program.'
    required: false
    default: ''
  source_dir:
    description: 'Path to the source directory.'
    required: false
    default: ''
  toolchain:
    description: 'Path to toolchain.'
    required: false
    default: ''
  build-type:
    description: 'Build type.'
    required: false
    default: 'Release'
  build-target:
    description: 'Targets to build instead of the default target'
    required: false
    default: ''
  install-prefix:
    description: 'Path where the library should be installed.'
    required: false
    default: '.local/usr'
  run-tests:
    description: 'Whether we should run tests.'
    required: false
    default: 'true'
  extra-args:
    description: 'Extra arguments to cmake configure command.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    - name: Setup msvc dev-cmd
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: CMake Build C++${{ inputs.cxxstd }}
      shell: bash
      working-directory: ${{ inputs.source_dir }}
      run: |
        set -xe

        # cmake args
        cc=${{ matrix.cc }}
        if [ "$cc" != "" ]; then
            if command -v $cc &> /dev/null; then
              cc="$(which $cc)"
            elif command -v /usr/bin/$cc &> /dev/null; then
              cc="/usr/bin/$cc"
            fi
            cmake_cc_path_args="-D CMAKE_C_COMPILER=$cc"
        else
            cmake_cc_path_args=
        fi

        cxx=${{ matrix.cxx }}
        if [ "$cxx" != "" ]; then
            if command -v $cxx &> /dev/null; then
              cxx="$(which $cxx)"
            elif command -v /usr/bin/$cxx &> /dev/null; then
              cxx="/usr/bin/$cxx"
            fi
            cmake_cxx_path_args="-D CMAKE_CXX_COMPILER=$cxx"
        else
            cmake_cxx_path_args=
        fi

        cxxstds=${{ inputs.cxxstd }}
        if [ "$cxxstds" == "" ]; then
            cxxstds=defaultcxx
        fi

        cmake_toolchain=${{ inputs.toolchain }}
        if [ "$cmake_toolchain" != "" ]; then
            cmake_toolchain_arg="-D CMAKE_TOOLCHAIN_FILE=$cmake_toolchain"
        else
            cmake_toolchain_arg=
        fi

        run_tests=${{ inputs.run-tests }}
        if [ "$run_tests" == "true" ]; then
          cmake_enable_test_args="-D BUILD_TESTING=ON"
        fi

        build_target=${{ inputs.build-target }}
        if [ "$build_target" != "true" ]; then
          target_args="--target $build_target"
        fi

        # iterate stds
        for cxxstd in ${cxxstds//,/ }
        do
            echo "==================================> CMAKE: C++$cxxstd"
            if [ "$cxxstd" == "defaultcxx" ]; then
                cmake_cxxstd_arg=""
                build_dir="build"
            else
                cmake_cxxstd_arg="-D CMAKE_CXX_STANDARD=$cxxstd"
                build_dir="build-$cxxstd"
            fi
            cmake -S . -B $build_dir -D CMAKE_BUILD_TYPE=${{ inputs.build-type }} $cmake_toolchain_arg $cmake_cxxstd_arg ${{ inputs.extra-args }} -D CMAKE_INSTALL_PREFIX=${{ inputs.install-prefix }} $cmake_cc_path_args $cmake_cxx_path_args $cmake_enable_test_args
            cmake --build $build_dir --config ${{ inputs.build-type }} -j ${{ steps.cpu-cores.outputs.count }} $target_args
            cmake --install $build_dir --config ${{ inputs.build-type }} --prefix prefix
            if [ "$run_tests" == "true" ]; then
              ctest --test-dir "$build_dir" -j ${{ steps.cpu-cores.outputs.count }} -C ${{ inputs.build-type }} --no-tests=error --progress --output-on-failure
            fi
        done

